version: 0.1

phases:
  install:
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region ap-northeast-2 s3 sync ./dist/ s3://codepipeline4makerlabs/ --acl=public-read --delete
